### ISSUE TITLE
Bug: Submitter doesn't allow overriding the frame range

### ISSUE THREAD

**Issue by yuanmich2** [aws-deadline/deadline-cloud-for-cinema-4d#52] opened 2024-06-25 15:55 UTC
### Expected Behaviour

I should be able to set a custom frame range when I open the submitter to submit a render.

### Current Behaviour

![image](https://github.com/aws-deadline/deadline-cloud-for-cinema-4d/assets/160265179/96a79a5a-0090-469f-9f1d-3656c368de03)
The field for overriding the frame range is grayed out and checking and unchecking the box next to it doesn't have any effect.
If you check the box and then close and reopen the submitter, however, the field will be editable.

### Reproduction Steps

Install the submitter.
Open the submitter and try to submit a job with a custom frame range.
If the checkbox was already checked by default, uncheck it, and close the submitter. Then reopen the submitter and try to add a custom frame range.

### Code Snippet

n/a

**Comment by lucaseck** [comment] 2024-06-25 16:56
Should be fixed once #54 is merged. Assuming that Pyside6 is being used the issue is there was a change from Pyside2->Pyside6 for how enums are handled and we now need to convert explicitly to an enum to do the comparison: https://doc.qt.io/qtforpython-6/considerations.html#the-new-python-enums

**Closed as completed** 2024-06-25 19:58 UTC
Labels: bug
